### ISSUE TITLE
MapComponent Class Suggestion

### ISSUE THREAD

**Issue by Sotanna** [Techkatz/Frogger#2]
# MapComponent Class
A MapComponent would contain the data to show
* Location
* Should it Loop?
  * And how often?
* Times
  * Start Time
  * End Time (when to remove)

All the elements of a Frogger map

* Logs
* Turtles
  * Lily Pads

would have their own classes, with their own individual settings, and tasks,
but they would all extend the class MapComponent, which would add the extra functionality
to make the game maps more complete

:stuck_out_tongue:

**Comment by Techkatz** [comment]
They would all follow the same speed and loup once they have gotten to the end of one side. This would give the illusion of the object moving, also I have a great idea for turtles that will blow your mind!

**Comment by Sotanna** [comment]
That's the main reason all the components should extend this centralized Object, each Sub-Class would detail the exacts of that component while the super class handles its Main functions

**Comment by Techkatz** [comment]
I think this is been resolved already.
